### ISSUE TITLE
OnceInADay feature to fix behaviour bug

### ISSUE THREAD

**Issue by LogGits** [Ben12345rocks/VotingPlugin#1246]
**Is your feature request related to a problem? Please describe.**
We give rewards out for voting on all sites but on of our vote links (topg) allows 12hr voting periods. The problem is AllSites will keep rewarding the player for every vote after all have been voted on. This means a player is able to get 2 rewards a day (if they vote on the topg after 12 hrs). We need all sites to only ever trigger once in a day.

**Describe the solution you'd like**
I need AllSites reward to include something like "Ignore duplicates" or "trigger once a day" or some toggle inside AllSites that disables this behaviour.

**Describe alternatives you've considered**
So many i want to die tbh. We tried WaitUntilVoteDelay but that causes desync with the website and the plugin causing loss of vote streaks players and improper reward sending.

Frustrated but loving the plugin keep up the great work 🙂 👍 

Version paper 1.18.2 build 318, VotingPlugin 6.9

**Comment by BenCodez** [comment]
From the config.yml:

    # If true, allsites will have an extra check to prevent duplicate allsites from being given
    ExtraAllSitesCheck: false

**Comment by LogGits** [comment]
Just for context I have always had that enabled apparently. I think i had to revert back to votesite delays because it wasn't working. Anyway i remove votesite delay so we can test again. Just need to check a few issues with you. 

1) Offline voting doesn't seem to trigger the AllSites rewards when the player rejoins, is that usual? It triggers cumulative and `EverySiteReward`, any ideas?
```yaml
AllSites: 
  ActionBar:
    Message: '&6Thank you for voting. Use the Vote Key at /warp crates'
    Delay: 30
  Commands:
    - cr give to %player% Vote 1
    - cmi broadcast %player% voted on all sites...
```
2) Cumulative voting setup like this gives a diamond for votes 3 and 4 (resulting in 2 diamonds) instead of just vote 3 (1 diamond) (is it possible to make it only give 1 diamond on vote 3 not give them a diamond for vote 4):
```yaml
Cumulative:
  # Number of votes required
  # Allows multiple cumulative rewards
  # Number be be around ' (E.g. '1')
  # Can have multiple listed here
  '3':
    Enabled: true
    # Wether or not votes must be made in same day/week
    # Useful if you want to require a certain number of voting sites to be voted on
    # for a daily/weekly reward instead of all of them
    VotesInSameDay: true
    VotesInSameWeek: false
    Rewards: 
      Items:
        Diamond:
          Material: 'DIAMOND'
          Amount: 1
```
3) We have files in Rewards folder and inside Directly Defined, are these all necessary if not which can i remove?
