### ISSUE TITLE
Link not formatted correctly

### ISSUE THREAD

**Issue by antiGriefer** [Ben12345rocks/VotingPlugin#1250]
**Versions**
Minecraft version 1.19
Plugin version 6.9.2

**Describe the bug**
![image](https://user-images.githubusercontent.com/67378144/179307668-a96356d1-74ec-467c-b066-9e9e5e4e5ae2.png)
The vote site is formatted incorrectly. 
Config:
```
VoteSites:
  Site1:
    Enabled: true
    Name: 'Site1'
    ServiceSite: 'minecraft-server-list.com'
    VoteURL: '[Text="ANY TEXT TO CLICK ON HERE",url="https://minecraft-server-list.com/server/456385/vote/"]'
    VoteDelay: 24
    DisplayItem:
      Material: 'IRON_PICKAXE'
      Amount: 1
    Rewards:
      Commands:
      - '/acb %player% 100'
      Messages:
        Player: 'Thank you for voting on our server'
```
**To Reproduce**
Enter the same config as shown above.
Side note. The link is still clickable

**Expected behavior**
Expected to just see [any text to click on here] 

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

**Additional context**
