### ISSUE TITLE
Offline vote milestones

### ISSUE THREAD

**Issue by IceWaffles** [Ben12345rocks/VotingPlugin#1260]
**Versions**
VotingPlugin version 6.9.5
git-PufferfishPlus-14 (MC: 1.19.2)*

**Describe the bug**
Essentially, ranks/milestones aren't run if the user hits said milestone when offline. The other rewards are given (if you have any), but not the milestones (and my milestone rewards I have as running a command to give a group/parent with LuckPerms). 

**To Reproduce**
1. Set a milestone in `specialrewards.yml` and have the command being run as `lp user %player% add <group>` when they hit the milestone
2. Vote while offline, and even if you reach the milestone (eg 10 or whatever it was set to) the command won't be run
3. I should note you can simulate/test this with admin vote commands; the bug still happens either way

**Expected behavior**
Ranks/group are given even if user is offline. Obviously, the command runs properly and the group is given if the user is online on the server.

**Additional context**
I already reported this on the discord previously, but now I'm locked out the discord because I can't provide a phone number. I could easily give more information; could you disable requiring a verified phone number on your discord server?

**Comment by BenCodez** [comment]
Can you send your specialrewards.yml? 

I have phone verification on discord to reduce spam, seem to get a lot of that if disabled.

**Comment by IceWaffles** [comment]
```
# To disable reward set value to []
# or remove entirely
# Eg:
# FirstVote: [] (All in one line)
# Rewards will be given if there is a reward to give
# 
# First vote rewards
FirstVote:
  Messages:
    Player: '&aYou voted for your first time!'
AllSites:
  Messages:
    Player: '&aYou voted on all sites in 1 day!'
Cumulative:
  '20':
    Enabled: false
    VotesInSameDay: false
    VotesInSameWeek: false
    VotesInSameMonth: false
    Rewards:
      Messages:
        Player: '&aYou got %cumulative% cumulative votes!'
VoteParty:
  Enabled: false
  VotesRequired: 20
  GiveAllPlayers: false
  ResetEachDay: false
  ResetWeekly: false
  ResetMonthly: false
  OnlyOncePerDay: false
  ResetExtraVotesMonthly: false
  CountFakeVotes: true
  UserVotesRequired: 0
  CountOfflineVotes: true
  Broadcast: '&cReached the vote party amount!'
  Commands: []
  Rewards:
    Commands:
    - say %player%
    Items:
      DIAMOND:
        Material: DIAMOND
        Amount: 1
ResetMilestonesMonthly: false
MileStones:
  '20':
    Enabled: true
    Rewards:
      Commands:
      - lp user %player% parent add sailor
      Messages:
        Player: '&aYou got %milestone% milestone votes!'
      RewardType: BOTH
  '70':
    Enabled: true
    Rewards:
      Commands:
      - lp user %player% parent add quartermaster
      Messages:
        Player: '&aYou got %milestone% milestone votes!'
      RewardType: BOTH
  '150':
    Enabled: true
    Rewards:
      Commands:
      - lp user %player% parent add firstmate
      Messages:
        Player: '&aYou got %milestone% milestone votes!'
      RewardType: BOTH
  '350':
    Enabled: true
    Rewards:
      Commands:
      - lp user %player% parent add captain
      Messages:
        Player: '&aYou got %milestone% milestone votes!'
      RewardType: BOTH
  '750':
    Enabled: true
    Rewards:
      Commands:
      - lp user %player% parent add admiral
      Messages:
        Player: '&aYou got %milestone% milestone votes!'
      RewardType: BOTH
VoteStreak:
  Day:
    '2':
      Enabled: false
      Rewards:
        Messages:
          Player: '&aYou voted for %Streak% %Type%''s in a row!'
  Week:
    '2':
      Enabled: false
      Rewards:
        Messages:
          Player: '&aYou voted for %Streak% %Type%''s in a row!'
  Month:
    '2':
      Enabled: false
      Rewards:
        Messages:
          Player: '&aYou voted for %Streak% %Type%''s in a row!'
  Requirement:
    UsePercentage: false
    Day: 50
    Week: 50
    Month: 50
VoteCoolDownEndedReward: []
AnySiteRewards: {}
LoginRewards: {}
LogoutRewards: {}
EnableMonthlyAwards: true
MonthlyAwards:
  '1':
    Rewards:
      Messages:
        Player: '&aYou came in first place in %TopVoter%!'
  '2':
    Rewards:
      Messages:
        Player: '&aYou came in second place in %TopVoter%!'
EnableWeeklyAwards: false
WeeklyAwards:
  '1':
    Rewards:
      Messages:
        Player: '&aYou came in first place in %TopVoter%!'
  '2':
    Rewards:
      Messages:
        Player: '&aYou came in second place in %TopVoter%!'
EnableDailyRewards: false
DailyAwards:
  '1':
    Rewards:
      Messages:
        Player: '&aYou came in first place in %TopVoter%!'
  '2':
    Rewards:
      Messages:
        Player: '&aYou came in second place in %TopVoter%!'
```
