### ISSUE TITLE
[Feature Request] VoteParty Reminder

### ISSUE THREAD

**Issue by SladeHazard** [Ben12345rocks/VotingPlugin#1307]
**Is your feature request related to a problem? Please describe.**
N/A

Hey, can you please add voteparty reminders which happen at certain Even numbers such as 100, 95, 90, 80. Similar to this:
![image](https://github.com/BenCodez/VotingPlugin/assets/45261094/02fade37-ad84-4611-9d06-f9a9000eaed8)

This is nothing related to manually adding a message when a player votes.. that is really spammy and useless

**Comment by BenCodez** [comment]
I can add that to the list to do. There is a way to do this with javascript technically but a little difficult

**Comment by SladeHazard** [comment]
probably not difficult to do with chatgpt if you can show me a small
example / placeholders

**Comment by BenCodez** [comment]
Just create reward files with the following, didn't test it but I think that works


    # Javascript expression which must be true in order to give this reward
    JavascriptExpression: 'VotingPlugin.getVoteParty().getNeededVotes() == 75'

**Comment by SladeHazard** [comment]
> Just create reward files with the following, didn't test it but I think that works
> 
> ```
> # Javascript expression which must be true in order to give this reward
> JavascriptExpression: 'VotingPlugin.getVoteParty().getNeededVotes() == 75'
> ```

I have added it and my reward file is called test.yml inside of the Rewards folder, how can I make sure that this reward is ran at 75 votes remaining and send the message then?

https://paste.denizenscript.com/View/116147

**Comment by BenCodez** [comment]
That alone should only let it run at 75 votes, just run the reward every vote

**Comment by SladeHazard** [comment]
> That alone should only let it run at 75 votes, just run the reward every vote

is there an example of how I can run the reward file (test.yml) here :? 
VoteSites.yml:
```
EverySiteReward:
  Commands:
  - crazycrate give physical vote 1 %player%
  - tokenmanager add {player} 200
  - lp user {player} permission settemp vote.reminder true 24h
  - gems add {player} 400
  - autominer give {player} 5
  - giveitem {player} minebomb#123
  - psound play {player} ENTITY_PLAYER_LEVELUP 1 1
  - titlemanager message {player} &c&lThanks for &4&lVOTING!\n&7&oEnjoy your rewards!
  Messages:
    Player: '&c&lARCHER &8&L» &7You received &d⛁200&7, &a⬧400 &7from voting.'
  OnlyOneLucky: true
  Lucky:
    '5':
      Commands:
      - crazycrate give physical vote 1 {player}
      Messages:
        Player: '&c&lARCHER &8&L» &aYou were lucky and received a vote crate'

```

I've read all the default configs and there seems to be no example. Are the rewards inside of the rewards folder run by default?
