### ISSUE TITLE
Votesites.yml

### ISSUE THREAD

**Issue by SladeHazard** [Ben12345rocks/VotingPlugin#1327]
1.12.2 Paper
Latest plugin version

Hey, I have a question. why is that lucky vote rewards are always being executed? I want the vote system to go through the chances and decide if the player received a lucky vote or not.. currently its making every vote a lucky vote, and the chance system is really bad, I have set the legendary key chance to "1" which should be 1%, people are getting it a lot still

CONFIG:

```
EverySiteReward:
  Commands:
  - 'crazycrate give physical vote 1 %player%'
  - 'lp user {player} permission settemp vote.reminder true 24h'
  - 'gems add {player} 5000'
  - 'autominer give {player} 5'
  - 'giveitem {player} minebomb'
  - 'psound play {player} ENTITY_PLAYER_LEVELUP 1 1'
  - 'titlemanager message {player} &c&lThanks for &4&lVOTING!\n&7&oEnjoy your rewards!'
  Messages:
    Player: '&c&lARCHER &8&L» &7You received &a⬧5000 &7from voting'
  OnlyOneLucky: true
  Lucky:
    # '1':
    #   Commands:
    #   - 'crazycrate give physical god 1 {player}'
    #   Messages:
    #     Player: '&c&lARCHER &8&L» &aYou were lucky and received a Legendary crate'
    '3':
      Commands:
      - 'giveitem {player} axepiece 1'
      Messages:
        Player: '&c&lARCHER &8&L» &aYou were lucky and received x1 &3&lO&b&lD&3&lI&b&lN &6&lAXE PIECE'

    '5':
      Commands:
      - 'egem add {player} 50000'
      - 'sendmessage * &c&lA&4&lP &7» &a{player} &7was lucky and received &a⬧50,000 &7from &a&l/vote'
    # '15':
    #   Commands:
    #   - 'crazycrate give physical mine 1 {player}'
    #   Messages:
    #     Player: '&c&lARCHER &8&L» &aYou were lucky and received a Mine crate'
    # '20':
    #   Commands:
    #   - 'voucher give plot 2 {player}'
    #   Messages:
    #     Player: '&c&lARCHER &8&L» &aYou were lucky and received x2 plots'
```
ignore the comments, i commented out because of how economy breaking it was, am i doing something wrong? is there another way of achieving my desired outcome?
