### ISSUE TITLE
View milestones in /vote gui

### ISSUE THREAD

**Issue by TomLewis** [Ben12345rocks/VotingPlugin#1396]
Can we please get a way to check milestones in-game as a player, via maybe /vote gui, so that they can see how far they have come and to track how many more they can do.

Also when I add new vote milestones, are these atomatically given to players that supassed the milestones already? How/when are these milestones being triggerd when the vote?

You could add lore to the milestone yaml so thats shown as the lore:

```yaml
  '15000':
    Enabled: true
    DisplayName: '&a&lVote 21'
    DisplayLore:
    - '&7You have voted 21 times!'
    - '&7Click to receive your reward!'
    Rewards:
      Money: 15000
      Messages:
        Player: '&8[&3VOTE&8] &aYou got %milestone% milestone votes!'
      Commands:
        Console:
        - crate give to %player% vote 21
```
