### ISSUE TITLE
Offline Vote Rewards

### ISSUE THREAD

**Issue by the-w41k3r** [Ben12345rocks/VotingPlugin#1402]
**Versions**
Spigot 1.21.1
VP: 6.17.5-SNAPSHOT

**Relevant information**
```yaml
Server1:
    Enabled: true
    Name: Site1
    ServiceSite: topminecraftservers.org
    VoteURL: https://topminecraftservers.org/vote/7050
    VoteDelay: 24
    ForceOffline: true
    DisplayItem:
      Material: DIAMOND
      Amount: 1
    Rewards:
      Commands:
      - 'discordsrv broadcast #1312319088604745768 `%player%` voted! Vote Party: **%votingplugin_votepartyvotesneeded%**.'
```

**Context**
Is this supposed to work like this for offline rewards? I want to be able to give rewards to players despite them being offline. Currently it does not work like this.

Also what would this option do?
```yaml
# Applies to PLUGINMESSAGING only
# Votes will be forwarded when specific player is online
# If set to false, rewards should still reward when player logs in (by default)
WaitForUserOnline: false```
