### ISSUE TITLE
How to get vote keys in all worlds

### ISSUE THREAD

**Issue by play-majesticmc-net** [Ben12345rocks/VotingPlugin#1410]
**Versions**
VotingPlugin 6.18  - Java MC 1.21.1

**Relevant information**
I got 4 Worlds using Multiverse-Core. Inventory is separated for each Wolds.

**Context**
How to get vote keys in all worlds? (6 keys in each Wolds.)
(Now I only get keys in the Wold I am in when I Vote.)

Thankx for your support
play.majesticmc.net

**Comment by BenCodez** [comment]
You'll have to make multiple rewards with them be whitelisted in one world or something like this (second example): https://github.com/BenCodez/VotingPlugin/wiki/World-Example

**Comment by play-majesticmc-net** [comment]
That was a fast answer :-) Thanx.

Do I add in in RealRewards.yml ?

**Comment by BenCodez** [comment]
where ever you set the rewards, can be directly in votesites.yml if you wanted

**Comment by play-majesticmc-net** [comment]
Like this:

  MinecraftServers_org:
    Enabled: true
    ServiceSite: MinecraftServers.org
    VoteURL: https://minecraftservers.org/vote/667945
    VoteDelay: 20.0
    DisplayItem:
      Material: STONE
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
      Commands:
        Console: 
        - ecrates key give %player% vote 1
   Rewards:
  Worlds:
  - world1
  - world2

**Comment by BenCodez** [comment]
That will only give in one world, but there is no rewards set for the sub rewards, use the example example from the link I sent, going to be the easiest way

**Comment by play-majesticmc-net** [comment]
Thanx, I will try it :-)

**Comment by play-majesticmc-net** [comment]
I cant get it to work :-( 
I have tried A LOT of configurations, now I tried with Reward1 and 2... still not working.
The "AdvancedWorld:" config only give a lot of errors.

I want to be able to get Keys in **world** AND **world_3**
Right now I only get a key in the world I am in when I voted.

Can you please see what I am doing wrong? :-)
(See attached file)
[VoteSites.txt](https://github.com/user-attachments/files/18427556/VoteSites.txt)


Thanx!! :-)

**Comment by BenCodez** [comment]
> I cant get it to work :-( I have tried A LOT of configurations, now I tried with Reward1 and 2... still not working. The "AdvancedWorld:" config only give a lot of errors.
> 
> I want to be able to get Keys in **world** AND **world_3** Right now I only get a key in the world I am in when I voted.
> 
> Can you please see what I am doing wrong? :-) (See attached file) [VoteSites.txt](https://github.com/user-attachments/files/18427556/VoteSites.txt)
> 
> Thanx!! :-)

What errors are you getting? AdvancedWorld is the easiest way. You'll have to make reward files to do the other way since you currently can't list multiple rewards another way (I'll add a way to do that in a few hours)

**Comment by play-majesticmc-net** [comment]
Sorry I dont remember the errors I got :-(

Q:
With the option "AdvancedWorld", do you use a Reward file, yml or do you add it in VoteSites.tml ?

**Comment by BenCodez** [comment]
> Sorry I dont remember the errors I got :-(
> 
> Q: With the option "AdvancedWorld", do you use a Reward file, yml or do you add it in VoteSites.tml ?

you can open the log files to see what you had. Can you send your votesites.yml when trying advancedworld? It can be used directly in votesites.yml or a reward file

**Comment by play-majesticmc-net** [comment]
Hi,
I tried to add "AdvancedWorld" again.....
Now I dont get any error message....BUT I dont get any keys.....in any worlds... :-(

See attached file

[VoteSites.txt](https://github.com/user-attachments/files/18457067/VoteSites.txt)

**Comment by BenCodez** [comment]
```  
  Best Minecraft Servers:
    Enabled: true
    ServiceSite: Best Minecraft Servers
    VoteURL: https://best-minecraft-servers.co/server-play-majesticmc-net.25999/vote
    VoteDelay: 20.0
    DisplayItem:
      Material: STONE
      Amount: 1
    Rewards:
      AdvancedWorld:
        World:
          Messages:
            Player: '&aThanks for voting on %ServiceSite%!'
          Commands:
          - say %player% in world
          - ecrates key give %player% vote 1
        World_3:
          Messages:
            Player: '&aThanks for voting on %ServiceSite%!'
          Commands:
          - say %player% in world_3
          - ecrates key give %player% vote 1
```





try that
