### ISSUE TITLE
Playsound is not working

### ISSUE THREAD

**Issue by DaddyRobLIVE** [Ben12345rocks/VotingPlugin#1417]
**Versions**
6.18.2 | 1.21.4

**Describe the bug**
```yml
Sound:
  # Enable or Disable Sound
  Enabled: true
  # Sound to play
  # 1.9 Sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # 1.8: https://jd.bukkit.org/org/bukkit/Sound.html 
  Sound: 'BLOCK_NOTE_BLOCK_CHIME'
  # Volume
  # Range: 0.0 to 1.0
  Volume: 1.0
  # Pitch
  # Range: 0.0 to 2.0
  Pitch: 1.0
```

This doesn't play a sound when a player votes

**To Reproduce**
1. Enable sound in reward.yml
2. Vote on a vote site
3. Sound won't play

**Expected behavior**
Sounds should be heard after voting

**Screenshots/Configs**
none
**Additional context**
none
