### ISSUE TITLE
Rewards Bug

### ISSUE THREAD

**Issue by Nat392** [Ben12345rocks/VotingPlugin#1424]
**Versions**
- AdvancedSlimePaper version 1.21.3-16525-dev/1.21.3@d5ade1e (2024-12-15T21:45:37Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
- VotingPlugin version 6.18.4-SNAPSHOT

**Describe the bug**
A player who had already collected the vote collected it again after a restart

**To Reproduce**
1. Vote on sites
2. Collect vote
3. Restart server
4. Connect and collect again

**Expected behavior**
Once a player has collected his vote, he may not collect it again.

**Comment by BenCodez** [comment]
Send your configs. Are you using a proxy setup?

**Comment by Nat392** [comment]
Yes, I use Velocity

Server Configs :

[config VotingPlugin.zip](https://github.com/user-attachments/files/19127707/config.VotingPlugin.zip)

**Comment by BenCodez** [comment]
Can you recreate the issue with /votingpluginbungee vote (player) (site)

**Comment by Nat392** [comment]
yes

```
>....[14:21:01 INFO]: &aVote sent for .OrBuilder on ServeurPrive
```
```
[14:21:01] [Server thread/INFO]: Added $200 to .OrBuilder balance. New balance: $6,294.
```
After restart :
```
[14:24:03 INFO]: Added $200 to .OrBuilder balance. New balance: $6,494.
```

**Comment by BenCodez** [comment]
You have the servers name different here? Server: skyblock

Send your bungeeconfig.yml

**Comment by Nat392** [comment]
Yes, I test on my dev server (exact backup of my server)

```yml
##########################################
# Bungee Setup 
# Only if using votingplugin bungee to send votes
# REQUIRES RESTART FOR CHANGES TO TAKE EFFECT
##########################################

# Plugin using bungee, requires plugin on bungee server
UseBungeecord: true

# What type of bungee setup
# Requires restart and set on all servers
# https://github.com/BenCodez/VotingPlugin/wiki/Bungeecord-Setups
# Available:
# SOCKETS
# PLUGINMESSAGING (Recommended)
# MYSQL
# REDIS (2nd Most Recommended)
BungeeMethod: PLUGINMESSAGING

# Use Redis for between server communication, set BungeeMethod to REDIS to use this
Redis:
  Host: localhost
  Port: 6379
# To get the user name, run redis-cli, if you set a password, run "auth <your password>" and if the out put is "OK" run "ACL USERS"
  Username: 'default'
  Password: ''
  # Set a prefix from an entire proxy network if using multi-proxy setup below
  Prefix: ''

# Enables more debug messages for communication between servers
# Use /votingpluginbungee status for testing communication
BungeeDebug: false

# Get the plugin to broadcast to all servers
# If false you need to enable 
# Only use for global rewards (one per network), otherwise you will get double broadcasts
BungeeBroadcast: false

# For pluginmessaging method only
# Whether to broadcast on cached votes
BungeeBroadcastAlways: false

# If true, the server won't broadcast votes
# To be used in conjuction with Broadcast setting on bungee
DisableBroadcast: false

# If true, offline rewards will be stored per server, rather than global
# This shouldn't need to be set unless you get alot of cross server rewards issues
# You can also specify the server within the rewards
# Requires server name below to be correct
PerServerRewards: false

# If true, milestones work per server
# Please note totals still sync, but milestones can be claimed on each server
# Needs to be set across all needed servers
PerServerMilestones: false

# If true, points will be given on a per server level
# Points will be added when server gets vote from bungee
PerServerPoints: false

# If true, plugin will trigger VotifierEvent
# Should allow some compability with other plugins
TriggerVotifierEvent: false

# If enabled plugin will give extra allsites reward if deterimned that it should
# E.g. user votes offline for 7 days, they will only get 1 allsites reward by default
# When enabled, they should get 7
# Only applies to PLUGINMESSAGING
# Recommend enabling ExtraAllSitesCheck in config.yml as well
GiveExtraAllSitesRewards: false

# What server this is in bungee (must match)
# Also can be applied to rewards
Server: dev

# Rewards from bungee vote party
# Gives to only players only
# Use regular voteparty rewards otherwise
# Can edit via /av gui
BungeeVotePartyRewards: {}

# List of commands to run on bungee party
# This runs a one time command only
BungeeVotePartyGlobalCommands: []

# Default is vp:vp, can be changed to prevent potential exploits
# Must match on all servers
# This setting requires a restart
PluginMessageChannel: "vp:vp"

# Use this to encrypt the plugin messages
# Must be set on all servers the same
# Copy secretkey.key file to all servers (They all must match)
# This setting requires a restart
PluginMessageEncryption: false

####################################################################################
# Global mysql data handle for between server commmunications
# This is NOT required for bungee voting to work
# This is still a WIP, use with caution
# This will create a different table then from users storing server info to process
#
# If you use this you need to enable this on BungeeSettings.yml on each server with votingplugin
# Make sure server name is set correctly in BungeeSettings.yml or this will not work correctly
# 
# Please use PLUGINMESSAGING for this, SOCKETS should work as well, but not fully tested
#
# This will make votes cache until time change has finished processing
# In the event a server is offline or time change fails, the time change process
# will continue after a set amount of time (in essense skipping a specific server)
# This will also respect blocked servers in bungeeconfig.yml
GlobalData:
  Enabled: false
  # Use existing mysql connection from config.yml
  UseMainMySQL: true
  # Mysql settings only used if above is false
  Host: ''
  # Default port is 3306
  Port: 3306 
  Database: ''
  Username: ''
  Password: ''
  # Max number of connections
  MaxConnections: 1
  # Must be the same on all servers
  Prefix: ''
  #UseSSL: true
  #PublicKeyRetrieval: false
  #Attempt to use mariadb driver
  #UseMariaDB: false

##########################################
# For socket setup
# Recommend to try PLUGINMESSAGING setup first
# Options hidden by default to avoid confusion
##########################################
# Options available here:
# https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-SOCKETS
```
